### PR TITLE
SystemUI: add telephony-ext so that imports can be resolved

### PR DESCRIPTION
**Pull request by akhilnarang**
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>

### CODE REVIEW

**Comment by akhilnarang** [comment]
@ashoksoni can you try this and let me know if it works?

**Comment by ashoksoni** [comment]
ok, sure.. Let me try this.

**Comment by ashoksoni** [comment]
Yup, build done, no more imports error.

**Comment by akhilnarang** [comment]
Cool, pick it into your branch please, the PR will be auto updated

**Comment by ashoksoni** [comment]
I opened a new PR already and closed the older one.

**Comment by akhilnarang** [comment]
Yeah saw it, cool👍

**Comment by ashoksoni** [comment]
@akhilnarang One question though, if in future I need to do this again with some other import, how do I find which Java library I need to add like this? Can I read it about it somewhere?

**Comment by akhilnarang** [comment]
Android.mk of the repo has the module name

**Comment by ashoksoni** [comment]
Ah, great. Thanks again.

**Pull request merged**
